### ISSUE TITLE
pyright failing with SIGABRT

### ISSUE THREAD

**Issue by ikamensh** [RobertCraigie/pyright-python#162] opened 2023-03-17 09:30 UTC
Fresh install of pyright with this wrapper fails with cryptic error. 

System: MacOs 12.6.3, Python3.11

```
(venv) ~/P/py11 $ pip install pyright                                                                                              (base) 10:26:13
Collecting pyright
  Downloading https://repo/artifactory/api/pypi/python-virtual/packages/packages/8e/00/37250aaef114b0d383487571ac8e3a6ff8691c68f165d25ca57839e7c952/pyright-1.1.299-py3-none-any.whl (17 kB)
Collecting nodeenv>=1.6.0
  Downloading https://repo/artifactory/api/pypi/python-virtual/packages/packages/96/a8/d3b5baead78adadacb99e7281b3e842126da825cf53df61688cfc8b8ff91/nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.11/site-packages (from nodeenv>=1.6.0->pyright) (60.2.0)
Installing collected packages: nodeenv, pyright
Successfully installed nodeenv-1.7.0 pyright-1.1.299
WARNING: You are using pip version 21.3.1; however, version 23.0.1 is available.
You should consider upgrading via the '/Users/kai7rng/PycharmProjects/py11/venv/bin/python -m pip install --upgrade pip' command.
(venv) ~/P/py11 $ pyright --version                                                                                                (base) 10:26:31
dyld[50242]: Library not loaded: '/usr/local/opt/icu4c/lib/libicui18n.71.dylib'
  Referenced from: '/usr/local/Cellar/node/18.10.0/bin/node'
  Reason: tried: '/usr/local/opt/icu4c/lib/libicui18n.71.dylib' (no such file), '/usr/local/lib/libicui18n.71.dylib' (no such file), '/usr/lib/libicui18n.71.dylib' (no such file), '/usr/local/Cellar/icu4c/72.1/lib/libicui18n.71.dylib' (no such file), '/usr/local/lib/libicui18n.71.dylib' (no such file), '/usr/lib/libicui18n.71.dylib' (no such file)
Traceback (most recent call last):
  File "/Users/kai7rng/PycharmProjects/py11/venv/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/Users/kai7rng/PycharmProjects/py11/venv/lib/python3.11/site-packages/pyright/cli.py", line 34, in entrypoint
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/Users/kai7rng/PycharmProjects/py11/venv/lib/python3.11/site-packages/pyright/cli.py", line 19, in main
    return run(*args, **kwargs).returncode
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kai7rng/PycharmProjects/py11/venv/lib/python3.11/site-packages/pyright/cli.py", line 25, in run
    pkg_dir = install_pyright(args, quiet=None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kai7rng/PycharmProjects/py11/venv/lib/python3.11/site-packages/pyright/_utils.py", line 61, in install_pyright
    node.run(
  File "/Users/kai7rng/PycharmProjects/py11/venv/lib/python3.11/site-packages/pyright/node.py", line 115, in run
    return subprocess.run(node_args, env=env, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/npm', 'install', 'pyright@1.1.299']' died with <Signals.SIGABRT: 6>.
```

**Comment by ikamensh** [comment] 2023-03-17 09:35
`brew install npm` solved the issue. Perhaps a call to `pyright --version` can be made as part of local build of this package though to surface errors, or a check that npm --version works.

**Comment by RobertCraigie** [comment] 2024-09-22 21:29
Thanks for the report, I'm going to close this as a duplicate of #231 as bundling the pyright npm package will fix this issue.

**Closed by RobertCraigie** 2024-09-22 21:29 UTC
